### ISSUE TITLE
contao managed edition

### ISSUE THREAD

**Issue by tkapet** [psi-4ward/docker-contao#3]
Can this docker container work also for contao managed edition in similar way?
thanks

**Comment by psi-4ward** [comment]
I think so, it's just PHP and Composer

**Comment by psi-4ward** [comment]
So it worked for you? Probably you can write down some notes for others?

**Comment by tkapet** [comment]
For contao managed version, in the help readme

i replaced: 
root at 53e71dbf4adc in /var/www ~ composer create-project contao/standard-edition website
with
root at 53e71dbf4adc in /var/www ~ composer create-project contao/**managed-edition** website

**Comment by psi-4ward** [comment]
Updated the README and pushed new Release with PHP 7.1
Can you check it?
