### ISSUE TITLE
Autodetect Contao4

### ISSUE THREAD

**Issue by Stefanmelz** [psi-4ward/docker-contao#4]
Hi,

kann es sein, dass der Autodetect mit der aktuellen composer.json nicht funktioniert. wir haben jetzt als Workaround ein Comment gesetzt, damit er das detected. Ist das so gedacht?

**Comment by psi-4ward** [comment]
Hi,
kannst du ein Beispiel der "aktuellen" composer.json Posten? Woran liegt es genau?

**Comment by psi-4ward** [comment]
closed due inactivity
