### ISSUE TITLE
DocumentRoot Problem in Contao 4.5

### ISSUE THREAD

**Issue by WLash** [psi-4ward/docker-contao#5]
Hi,
in contao 4.5 the document root is not set because of the second condition you use in 
https://github.com/psi-4ward/docker-contao/blob/f9c6bfcd1aa999f861c5187b815369684cd45cfc/rootfs/run-httpd#L4 
I have to add a nonsense line in composer.json to satisfy the script. ;)

**Comment by psi-4ward** [comment]
So whats the way to detect the contao version ?

**Comment by WLash** [comment]
In the require section of the composer.json would be some version numbers from different core bundles
`"require": {
"php": "^7.1",
"contao/calendar-bundle": "^4.5",
"contao/comments-bundle": "^4.5",
"contao/faq-bundle": "^4.5",
"contao/listing-bundle": "^4.5",
"contao/manager-bundle": "4.5.*",
"contao/news-bundle": "^4.5",
"contao/newsletter-bundle": "^4.5"
},`
Maybe could this be an approach?

**Comment by psi-4ward** [comment]
Pls test latest in about 30 Minutes, Docker-Hub needs some time to build the image.

**Comment by WLash** [comment]
It works. Thanks!

**Comment by psi-4ward** [comment]
Nice, I'll tag a new version
